EC-CUBE/ec-cube.github.io

plugin_console.md

uninstallに関するせつめいだったので、

---

update.md

composerコマンドの誤りを修正

---

api_authorization.md

- .htaccess の設定情報を追記
- scope を product_read, product_write に修正

CRUD API の情報を反映

---

cookbook-1-cube3-customize-admin-add.md
plugin-test.md
spec-directory-structure.md
tutorial-1.md
tutorial-10.md
tutorial-11.md
tutorial-12.md
tutorial-13.md
tutorial-2.md
tutorial-3.md
tutorial-4.md
tutorial-5.md
tutorial-6.md
tutorial-7.md
tutorial-8.md
tutorial-9.md

スニペット読み込みパス修正

---

Source/tutorial_10/CrudController_add_save.php
Source/tutorial_10/crud_top_add_save_loop.twig
Source/tutorial_11/CrudController_add_repository.php
Source/tutorial_11/CrudController_modified_repository.php
Source/tutorial_12/crud_edit_before.twig
Source/tutorial_12/crud_top_add_edit.twig
Source/tutorial_13/crud_top_add_delete.twig
_includes/head.html
requirement.md
tutorial-10.md
tutorial-8.md

フラッシュメッセージの説明を修正

---

web-api-doc.md

WEBAPIプラグインページ一部修正

---

_includes/head.html

descriptionタグ表示追加

---

guideline/plugin-pagedelete.md

利用しないページの削除を追加

---

guideline/plugin-table.md

テーブルの作成を追加

---

pages/guideline/guideline_development.md
pages/quickstart/quickstart_install.md

- composer create-project を使用した解説に修正
- #127 の一部修正漏れを修正

composer create-project を使用した解説に修正

---

pages/plugin/plugin-tutorial.md

1文字抜けtypoの修正

---

pages/collaboration/collaboration_githubflow.md

古い話ですが、不要なコミットはまとめて (rebaseして) PRしてもらいたいという内容が以前Gitterで上がっておりましたので、それを反映してみました。
いかがでしょうか。
参考：https://gitter.im/EC-CUBE/ec-cube?at=56777771f240f5a00417764b

【提案】リベース (不要なコミットをまとめる) の説明を追加

---

index.md
pages/customize/customize_entity.md
pages/customize/customize_formtype.md
pages/customize/customize_repository.md
pages/customize/customize_service.md
pages/customize/customize_symfony.md
pages/customize/customize_template.md
pages/multilingualization/spec.md
pages/plugin/plugin-sample.md
pages/plugin/plugin-spec.md
pages/quickstart/requirement.md

- 動作確認済みバージョンは *TBD* にしています。
- ブラウザの対応バージョンは以下のサイトを参考にアップデートしました。
- https://developer.apple.com/support/app-store/
- https://developer.android.com/about/dashboards/index.html
- https://www.microsoft.com/ja-jp/windows/lifecycle/iesupport/

システム要件のアップデート

---

pages/customize/customize_symfony.md

以下について記載しています
- Symfony Event
- Command
- Doctrine Event
SymfonyのBundleの利用方法とかも、今後追加していければと思います。
現状Acme配下がコンテナに登録されていないため、以下もマージお願いします。
https://github.com/EC-CUBE/ec-cube/pull/2949

Symfonyの機構を使ったカスタマイズ

---

pages/customize/customize_controller.md

書きたいことはいろいろありますが、基本的なルーティングの追加とカスタマイズを記載しました。

コントローラのカスタマイズのページを記載

---

pages/customize/customize_formtype.md

- FormExtensionを使った拡張 を記載しています
- Entityからフォームを生成した拡張については、Entityの章に記載するので、この頁からは後ほどリンクを張ります。

FormTypeカスタマイズのページを記載

---

_config.yml
_data/sidebars/home_sidebar.yml
_data/topnav.yml
index.md

- サイドナビのリンク先を変更しました。
- 修正と3.n向けに記載やリンク先を変更しました。

サイドナビの修正と3.n向けに記載やリンク先を変更。

---

pages/quickstart/requirement.md

変更点
- PHP7.１以降に変更
- PostgreSQL10 対応
https://github.com/EC-CUBE/ec-cube/pull/3401

Doctrineバージョンアップに伴い、システム要件をアップデート

---

pages/plugin/spec.md

- アーカイブ作成コマンドの修正
- composer.jsonの説明を記述

プラグイン仕様の修正

---

pages/customize/customize_repository.md

QueryCustomizer サンプルの namespace が間違っていたため修正
see https://github.com/EC-CUBE/ec-cube/pull/3629

QueryCustomizer サンプルの namespace を修正

---

pages/customize/customize_formtype.md

以下の対応
https://github.com/EC-CUBE/ec-cube.github.io/issues/208

FormTypeのカスタマイズページのファイル名を修正

---

index.md

Reverts EC-CUBE/ec-cube.github.io#217
4系の内容を3系のブランチへマージしてしまっていたので切り戻し

Revert "XDテンプレートについて追記"

---

pages/quickstart/update.md

スキーマ更新注釈追加

---

pages/quickstart/install.md

パーミッションの設定例で不意にmarkdownになってしまっていたので `` で囲んだ

パーミッションの設定例で不意にmarkdownになってしまっていたので `` で囲んだ

---

pages/plugin/plugin_console-plugin.md

開発コミュニティより
https://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=21658&forum=19&post_id=90714#forumpost90714
- コピペできちんと動作するように修正
- コマンドの実行内容とコマンド名が一致するようにサンプルを修正
- タイトルや説明文を見直し

コンソールプラグインの作成方法を見直し

---

pages/quickstart/update_3_0_18.md

メルマガプラグインのマイグレーションの実装を元に、サンプルコードを追加しました。

マイグレーションサンプルの追加

---

pages/quickstart/update.md

3.0.18アップデート手順の修正

---

pages/quickstart/requirement.md

4.0.2 ver7.3

---

_config.yml
documents/updatedoc/3.0.11/template-diff_Mypage_favorite.twig.html
documents/updatedoc/3.0.11/template-diff_Product_detail.twig.html
documents/updatedoc/3.0.11/template-diff_block.twig.html
pages/plugin/tutorial-generate3013.md

LOCKONからEC-CUBEへ変更

---

_config.yml
documents/updatedoc/4.0.1/Contact_index_twig.htm
documents/updatedoc/4.0.1/Entry_index_twig.htm
documents/updatedoc/4.0.1/Mypage_change_twig.htm
documents/updatedoc/4.0.1/Mypage_delivery_edit_twig.htm
documents/updatedoc/4.0.1/Shopping_index_twig.htm
documents/updatedoc/4.0.1/Shopping_nonmember_twig.htm
documents/updatedoc/4.0.1/Shopping_shipping_edit_twig.htm
documents/updatedoc/4.0.1/Shopping_shipping_multiple_edit_twig.htm
pages/plugin/tutorial-generate3013.md

4.0ブランチのLOCKON表記をEC-CUBEへ変更

---

pages/quickstart/requirement.md

公式サイトに合わせて動作確認済みのPHPバージョンを7.2に更新しました。

動作確認済みのPHPバージョンを7.2に更新

---

_data/sidebars/home_sidebar.yml

【doc4】サイドバーにデザインカスタマイズのリンクを追加

---

pages/plugin/bp/plugin_bp_config.md

ドキュメント内のリンク切れを修正しました
https://doc.ec-cube.net/plugin_bp_config

サービスプロバイダページへのリンクを修正

---

pages/quickstart/install.md

- Docker を使用したインストール方法を追記
- Windows 環境での注意点を追記
- ダウンロードURLのファイル名が古かったため修正

Docker を使用したインストール方法を追記

---

css/customstyles.css

可読性をよくするために、h2のテキストの下にアンダーラインを追加。

---

pages/workaround-product-tax-rule.md

- 3系ドキュメント
- 商品を指定して更新するSQLが間違っていたのを修正しました。
- 変更後のSQLを実行して、不具合が解消することを確認しました。

商品を指定して更新するSQLが間違っていたのを修正。
